export enum TableOperationsType {
    PAGE_CHANGED = 'PAGE_CHANGED',
    PAGE_SIZE_CHANGED = 'PAGE_SIZE_CHANGED',
    PAGE_SORT_CHANGED = 'PAGE_SORT_CHANGED',
    PAGE_FILTER_CHANGED = 'PAGE_FILTER_CHANGED',
    TOTAL_COUNT_CHANGED = 'TOTAL_COUNT_CHANGED',
}
